name: Update lang files
on:
  pull_request:
    branches:
      - main
      - develop
    types: closed

jobs:
  update_date:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          # Fetch full depth, otherwise the last step overwrites the last commit's parent, essentially removing the graph.
          fetch-depth: 0

      - name: Update version.txt
        run: |
          npm install
          npm run transform-lang
      - name: Amend the last commit
        run: |
          git config --global user.email "wonnyohamester@outlook.com"
          git config --global user.name "Automation"
          git commit -a --amend --no-edit
          git push --force-with-lease
          echo "Complete"
